// Données mockup selon la structure exacte des APIs Django Backend

import type {
  CategoriesResponse,
  QuizResponse,
  IdeasResponse,
  ResourcesResponse,
  HealthResponse,
} from '@/types/api';

// ============= GET /api/categories/ ✅ =============
export const mockCategoriesResponse: CategoriesResponse = {
  categories: [
    {
      id: 1,
      name: 'Système d\'exploitation',
      slug: 'os',
      title: 'Système d\'exploitation des PC',
      subtitle: 'Choisis ce que tu fais des postes existants dans ton lycée pour équiper 50 salles de cours',
      icon: 'Laptop',
      step: 1,
      total_steps: 4,
      options: [
        {
          id: 1,
          name: 'Windows 11 neuf',
          description: 'Acheter 50 nouveaux PC sous Windows 11. Matériel neuf avec licences Windows, confort d\'usage immédiat, mais coûts élevés et déchets électroniques importants.',
          impact_cost: -20,
          impact_ecology: -25,
          impact_autonomy: -30,
          impact_inclusion: 0,
          tags: ['Coût élevé', 'Impact écologique mauvais', 'Autonomie faible'],
        },
        {
          id: 2,
          name: 'Linux sur anciens PC',
          description: 'Garder les anciens PC et installer Linux. Réemploi des machines existantes, logiciels libres, prolongation de la durée de vie de 5+ ans. Sobriété et autonomie.',
          impact_cost: 30,
          impact_ecology: 35,
          impact_autonomy: 40,
          impact_inclusion: 10,
          tags: ['Coût faible', 'Très bon pour l\'écologie', 'Autonomie forte'],
        },
      ],
    },
    {
      id: 2,
      name: 'Suite bureautique',
      slug: 'office',
      title: 'Suite bureautique',
      subtitle: 'Outils de traitement de texte, tableur et présentation pour tous les enseignants et élèves',
      icon: 'FileText',
      step: 2,
      total_steps: 4,
      options: [
        {
          id: 3,
          name: 'Microsoft Office',
          description: 'Microsoft Office avec licences payantes annuelles. Suite connue et répandue, mais écosystème fermé et coût récurrent important.',
          impact_cost: -15,
          impact_ecology: -5,
          impact_autonomy: -25,
          impact_inclusion: -5,
          tags: ['Licences payantes', 'Écosystème fermé'],
        },
        {
          id: 4,
          name: 'LibreOffice',
          description: 'LibreOffice, logiciel libre et gratuit. Gratuit, libre, adaptable. Formats ouverts et plus d\'autonomie pour l\'établissement. Compatible avec Office.',
          impact_cost: 25,
          impact_ecology: 10,
          impact_autonomy: 35,
          impact_inclusion: 15,
          tags: ['Gratuit', 'Logiciel libre', 'Autonomie renforcée'],
        },
      ],
    },
    {
      id: 3,
      name: 'Stockage des données',
      slug: 'storage',
      title: 'Stockage des données',
      subtitle: 'Hébergement des documents pédagogiques et données personnelles des élèves et enseignants',
      icon: 'Cloud',
      step: 3,
      total_steps: 4,
      options: [
        {
          id: 5,
          name: 'Cloud Big Tech',
          description: 'Cloud d\'une grande entreprise hors Europe. Facile à déployer, mais questions de souveraineté des données et conformité RGPD délicate.',
          impact_cost: -10,
          impact_ecology: -15,
          impact_autonomy: -35,
          impact_inclusion: -10,
          tags: ['Dépendance forte', 'Souveraineté faible'],
        },
        {
          id: 6,
          name: 'Hébergeur européen',
          description: 'Hébergeur européen ou solution locale. Plus transparent, conforme RGPD, données en France ou Europe. Respect de la vie privée des élèves.',
          impact_cost: 15,
          impact_ecology: 20,
          impact_autonomy: 30,
          impact_inclusion: 20,
          tags: ['Plus souverain', 'Vie privée protégée'],
        },
      ],
    },
    {
      id: 4,
      name: 'Politique de renouvellement',
      slug: 'renewal',
      title: 'Politique de renouvellement du matériel',
      subtitle: 'Stratégie de gestion du parc informatique sur le long terme (5-10 ans)',
      icon: 'RefreshCw',
      step: 4,
      total_steps: 4,
      options: [
        {
          id: 7,
          name: 'Remplacement fréquent',
          description: 'Remplacement des PC tous les 3 ans. Parc toujours récent, mais déchets électroniques importants et coûts élevés sur la durée.',
          impact_cost: -25,
          impact_ecology: -40,
          impact_autonomy: -10,
          impact_inclusion: 0,
          tags: ['Beaucoup de déchets', 'Coûts importants'],
        },
        {
          id: 8,
          name: 'Réemploi et réparation',
          description: 'Réemploi, réparation, durée de vie prolongée. Sobriété numérique, moins de déchets, coûts maîtrisés sur le long terme. Cohérent avec NIRD.',
          impact_cost: 30,
          impact_ecology: 45,
          impact_autonomy: 15,
          impact_inclusion: 10,
          tags: ['Sobriété', 'Moins de déchets', 'Coût maîtrisé'],
        },
      ],
    },
  ],
};

// ============= GET /api/quiz/ ✅ =============
export const mockQuizResponse: QuizResponse = {
  questions: [
    {
      id: 1,
      question: 'Un ordinateur sous Windows 10 ne peut plus être utilisé après 2025',
      is_true: false,
      explanation: 'Faux ! Avec Linux, un PC peut continuer à fonctionner pendant des années même après la fin du support Windows.',
      category: 'os',
      difficulty: 'facile',
    },
    {
      id: 2,
      question: 'LibreOffice est compatible avec les fichiers Microsoft Office',
      is_true: true,
      explanation: 'Vrai ! LibreOffice peut ouvrir, modifier et enregistrer des fichiers aux formats .docx, .xlsx, .pptx de Microsoft Office.',
      category: 'office',
      difficulty: 'facile',
    },
    {
      id: 3,
      question: 'Les données hébergées dans le cloud sont toujours en France',
      is_true: false,
      explanation: 'Faux ! De nombreux services cloud hébergent les données aux États-Unis ou ailleurs. Il faut vérifier la localisation des serveurs.',
      category: 'storage',
      difficulty: 'moyen',
    },
    {
      id: 4,
      question: 'Recycler un ordinateur produit moins de CO2 que d\'en fabriquer un neuf',
      is_true: true,
      explanation: 'Vrai ! La fabrication d\'un ordinateur représente 80% de son impact environnemental total. Le réemploi est donc essentiel.',
      category: 'renewal',
      difficulty: 'facile',
    },
    {
      id: 5,
      question: 'Les logiciels libres sont toujours gratuits',
      is_true: true,
      explanation: 'Vrai ! Les logiciels libres sont gratuits et leur code source est accessible. On peut les utiliser, les modifier et les redistribuer librement.',
      difficulty: 'moyen',
    },
    {
      id: 6,
      question: 'Linux est plus difficile à utiliser que Windows',
      is_true: false,
      explanation: 'Faux ! Les distributions modernes comme Ubuntu ou Linux Mint sont aussi simples que Windows pour un usage bureautique basique.',
      category: 'os',
      difficulty: 'moyen',
    },
    {
      id: 7,
      question: 'Le RGPD impose de protéger les données des élèves',
      is_true: true,
      explanation: 'Vrai ! Le RGPD impose aux établissements scolaires de protéger les données personnelles des élèves et de savoir où elles sont hébergées.',
      category: 'storage',
      difficulty: 'moyen',
    },
    {
      id: 8,
      question: 'Un PC de 10 ans ne peut plus être utilisé',
      is_true: false,
      explanation: 'Faux ! Avec Linux et des logiciels légers, un PC de 10 ans peut encore servir pour de la bureautique, navigation web, etc.',
      category: 'renewal',
      difficulty: 'facile',
    },
  ],
};

// ============= GET /api/ideas/ ✅ =============
export const mockIdeasResponse: IdeasResponse = {
  count: 5,
  results: [
    {
      id: 1,
      title: 'Club Linux au lycée',
      description: 'Créer un club informatique où les élèves apprennent Linux et contribuent à des projets open source.',
      author_name: 'Marie Dupont',
      school_name: 'Lycée Victor Hugo, Paris',
      is_approved: true,
      created_at: '2024-11-15T10:30:00Z',
    },
    {
      id: 2,
      title: 'Atelier de reconditionnement',
      description: 'Organiser des ateliers où les élèves reconditionnent des vieux PC pour les donner à des familles dans le besoin.',
      author_name: 'Thomas Martin',
      school_name: 'Collège Jean Moulin, Lyon',
      is_approved: true,
      created_at: '2024-11-20T14:15:00Z',
    },
    {
      id: 3,
      title: 'Migration progressive vers LibreOffice',
      description: 'Commencer par former les enseignants volontaires, puis généraliser progressivement.',
      author_name: 'Sophie Bernard',
      school_name: 'Lycée Pasteur, Strasbourg',
      is_approved: true,
      created_at: '2024-12-01T09:00:00Z',
    },
    {
      id: 4,
      title: 'Serveur Nextcloud pour l\'établissement',
      description: 'Installer un serveur Nextcloud auto-hébergé pour remplacer Google Drive.',
      author_name: 'Lucas Petit',
      school_name: 'Lycée Diderot, Marseille',
      is_approved: true,
      created_at: '2024-12-02T16:45:00Z',
    },
    {
      id: 5,
      title: 'Journée du Libre',
      description: 'Organiser une journée dédiée aux logiciels libres avec des ateliers, conférences et démonstrations.',
      author_name: 'Emma Rousseau',
      school_name: 'Collège Marie Curie, Toulouse',
      is_approved: true,
      created_at: '2024-12-03T11:20:00Z',
    },
  ],
};

// ============= GET /api/resources/ ⭐ =============
export const mockResourcesResponse: ResourcesResponse = {
  count: 8,
  results: [
    {
      id: 1,
      title: 'Installer Linux dans votre établissement',
      type: 'guide',
      description: 'Guide complet pour migrer vos ordinateurs vers Linux Ubuntu ou Debian',
      url: 'https://example.com/guide-linux',
      tags: ['linux', 'installation', 'débutant'],
    },
    {
      id: 2,
      title: 'LibreOffice : Alternative à Microsoft Office',
      type: 'tool',
      description: 'Suite bureautique libre et gratuite compatible avec les formats Microsoft',
      url: 'https://fr.libreoffice.org/',
      tags: ['bureautique', 'logiciel libre'],
    },
    {
      id: 3,
      title: 'Framalibre : Annuaire du Libre',
      type: 'site',
      description: 'Plus de 1500 logiciels libres pour remplacer vos outils propriétaires',
      url: 'https://framalibre.org/',
      tags: ['logiciels libres', 'annuaire'],
    },
    {
      id: 4,
      title: 'La Nuit de l\'Info - NIRD',
      type: 'article',
      description: 'Découvrez le projet NIRD : Numérique Inclusif, Responsable et Durable',
      url: 'https://www.nuitdelinfo.com/',
      tags: ['NIRD', 'souveraineté numérique'],
    },
    {
      id: 5,
      title: 'Nextcloud : Cloud souverain',
      type: 'tool',
      description: 'Solution d\'hébergement de fichiers auto-hébergée et sécurisée',
      url: 'https://nextcloud.com/',
      tags: ['cloud', 'hébergement', 'données'],
    },
    {
      id: 6,
      title: 'Emmabuntüs : Linux pour le réemploi',
      type: 'tool',
      description: 'Distribution Linux spécialement conçue pour redonner vie aux vieux PC',
      url: 'https://emmabuntus.org/',
      tags: ['linux', 'réemploi', 'écologie'],
    },
    {
      id: 7,
      title: 'April : Association de promotion du Libre',
      type: 'article',
      description: 'Pionnière du logiciel libre en France depuis 1996',
      url: 'https://www.april.org/',
      tags: ['association', 'libre', 'communauté'],
    },
    {
      id: 8,
      title: 'Framasoft : Dégooglisons Internet',
      type: 'site',
      description: 'Services libres et éthiques pour se libérer des GAFAM',
      url: 'https://framasoft.org/',
      tags: ['association', 'services', 'GAFAM'],
    },
  ],
};

// ============= GET /api/health/ ⭐ =============
export const mockHealthResponse: HealthResponse = {
  status: 'ok',
  message: 'API Backend Django is running (MOCKUP)',
  timestamp: new Date().toISOString(),
};
